create table tb_comment (created_at timestamp(6) with time zone, id bigserial not null, post_id bigint, user_id bigint, text varchar(255), primary key (id));
create table tb_post (created_at timestamp(6) with time zone, id bigserial not null, user_id bigint, text varchar(255), primary key (id));
create table tb_role (id bigserial not null, authority varchar(255), primary key (id));
create table tb_user (id bigserial not null, email varchar(255) unique, name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id));
alter table if exists tb_comment add constraint FKebak8c8m45519djplq0wanuj3 foreign key (post_id) references tb_post;
alter table if exists tb_comment add constraint FK45c1cuqlljd60ihc9j0962ekq foreign key (user_id) references tb_user;
alter table if exists tb_post add constraint FKhx7a7k3pf66vpddqg5pr12anw foreign key (user_id) references tb_user;
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_user(name, email, password) VALUES ('José Rocha', 'jose@gmail.com', '$2a$10$eDKQQCSVwERFyi5xTlpPKudmw8P/Q4Dum7b4bdh4WnIA3xtB6zEzy');
INSERT INTO tb_user(name, email, password) VALUES ('Maria Sousa', 'maria@gmail.com', '$2a$10$eDKQQCSVwERFyi5xTlpPKudmw8P/Q4Dum7b4bdh4WnIA3xtB6zEzy');
INSERT INTO tb_role(authority) VALUES ('ROLE_USER');
INSERT INTO tb_role(authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role(user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role(user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role(user_id, role_id) VALUES (2, 2);
INSERT INTO tb_post(text, created_at, user_id) VALUES ('Eai galera!', '2023-07-27 15:31:22', 2);
INSERT INTO tb_post(text, created_at, user_id) VALUES ('Bom dia!', '2023-07-27 09:31:22', 2);
INSERT INTO tb_post(text, created_at, user_id) VALUES ('Só testando aqui :D', '2023-07-27 11:31:22', 1);
INSERT INTO tb_comment(text, created_at, user_id, post_id) VALUES ('Opa, tudo bom?', '2023-07-28 15:31:22', 1, 1);
create table tb_comment (created_at timestamp(6) with time zone, id bigserial not null, post_id bigint, user_id bigint, text varchar(255), primary key (id));
create table tb_post (created_at timestamp(6) with time zone, id bigserial not null, user_id bigint, text varchar(255), primary key (id));
create table tb_role (id bigserial not null, authority varchar(255), primary key (id));
create table tb_user (id bigserial not null, email varchar(255) unique, name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id));
alter table if exists tb_comment add constraint FKebak8c8m45519djplq0wanuj3 foreign key (post_id) references tb_post;
alter table if exists tb_comment add constraint FK45c1cuqlljd60ihc9j0962ekq foreign key (user_id) references tb_user;
alter table if exists tb_post add constraint FKhx7a7k3pf66vpddqg5pr12anw foreign key (user_id) references tb_user;
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_user(name, email, password) VALUES ('José Rocha', 'jose@gmail.com', '$2a$10$eDKQQCSVwERFyi5xTlpPKudmw8P/Q4Dum7b4bdh4WnIA3xtB6zEzy');
INSERT INTO tb_user(name, email, password) VALUES ('Maria Sousa', 'maria@gmail.com', '$2a$10$eDKQQCSVwERFyi5xTlpPKudmw8P/Q4Dum7b4bdh4WnIA3xtB6zEzy');
INSERT INTO tb_role(authority) VALUES ('ROLE_USER');
INSERT INTO tb_role(authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role(user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role(user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role(user_id, role_id) VALUES (2, 2);
INSERT INTO tb_post(text, created_at, user_id) VALUES ('Eai galera!', '2023-07-27 15:31:22', 2);
INSERT INTO tb_post(text, created_at, user_id) VALUES ('Bom dia!', '2023-07-27 09:31:22', 2);
INSERT INTO tb_post(text, created_at, user_id) VALUES ('Só testando aqui :D', '2023-07-27 11:31:22', 1);
INSERT INTO tb_comment(text, created_at, user_id, post_id) VALUES ('Opa, tudo bom?', '2023-07-28 15:31:22', 1, 1);
